### PR TITLE
Allow customization of ancestorSeparator. Fixes #19

### LINKED ISSUE #19: Allow customization of separator between ancestor titles
In the [code](https://github.com/palmerj3/jest-junit/blob/master/utils/buildJsonResults.js#L49), I saw the `ancestorTitles` are concatenated using a space. In Jest, by default they use the `›` character to concatenate the strings between hierarchies and I think it would be good to allow users to customize this character. 

If you are agreeable with this I can create a PR to implement this. I'm thinking of implementing this through the env variable like how the class name template is done.

### PR DESCRIPTION
**Pull request by yangshun**
Not sure if I need to write tests for this. I did test locally on my own project with the config change via `package.json` and environment variable.

### CODE REVIEW

**Comment by palmerj3** [comment]
Hey @yangshun awesome!

Please write a test for this and ping me when it's ready then we can go ahead and merge. Also since the configuration is a bit hard to explain to an average user would you mind also adding a small section to the bottom of the readme which shows example usage and the sample xml output it would generate?

Thank you very much

**Comment by yangshun** [comment]
@palmerj3 Have a look, I improved the README by quite a bit with more examples. It should be clearer now.

**Comment by palmerj3** [comment]
Nicely done @yangshun!

**Comment by palmerj3** [comment]
Published 2.1.0 with this feature - https://github.com/palmerj3/jest-junit/releases/tag/v2.1.0

**Pull request merged**
