### PR TITLE
Add package.json config option

### PR DESCRIPTION
**Pull request by jsg2021**
This allows you to define your options into the package.json (just like jest does)

### CODE REVIEW

**Comment by palmerj3** [comment]
@jsg2021 nice! Good idea. I would much rather not introduce another dependency if we don't have to so would you mind replacing read-pkg with a simple `require(path.join(process.cwd(), 'package.json'))`

Thanks!

**Comment by jsg2021** [comment]
Sure, I just used the same method jest did. I'll update it.

**Comment by palmerj3** [comment]
👍 nice work!

**Comment by palmerj3** [comment]
@jsg2021 this is now part of 1.4.0 and has been published. Thanks again! https://github.com/palmerj3/jest-junit/releases/tag/v1.4.0

**Comment by jsg2021** [comment]
awesome. thanks!

**Pull request merged**
