### PR TITLE
Add filename and filepath to classname and title templates strings

### PR DESCRIPTION
**Pull request by samertm**
This is useful for making the combination of classname + title unique, which need depend on at Dropbox.

### CODE REVIEW

**Comment by palmerj3** [comment]
@samertm thanks again for the contributions! If you wouldn't mind would you also add a test (if possible) here for this? https://github.com/palmerj3/jest-junit/blob/master/__tests__/buildJsonResults.test.js

**Comment by samertm** [comment]
Yup!

**Comment by samertm** [comment]
Just updated the commit.

**Comment by palmerj3** [comment]
Perfect thank you!

**Comment by palmerj3** [comment]
@samertm just published 3.4.1 with these changes. Thanks again!

**Comment by samertm** [comment]
Thanks for the fast turn-around!

**Pull request merged**
