### PR TITLE
Allowed using the test file path as the suite name

### LINKED ISSUE #13: When no outer `describe()` is used, testsuite name is undefined
If a unit test is written without an outer `describe()` -- which by the way should be optional, then `jest-junit` sets the testsuite name to `undefined`.

There should be a way to configure using the test file path instead of the outermost `describe()`.

### PR DESCRIPTION
**Pull request by danjamin**
- configurable via both package.json and an ENV variable

fixes #13

### CODE REVIEW

**Comment by palmerj3** [comment]
@danjamin I love it! I was actually needing something just like this today so excellent timing on your part :)

I have one comment on the PR that I'd like you to address and then I'll go ahead and merge and publish a new patch release.

Thanks and great work!!

**Comment by palmerj3** [comment]
@danjamin also please add a simple test which ensures that the suitename is set as intended

**Comment by danjamin** [comment]
@palmerj3 ok, so I had to rework a few things to make what I needed to test, well, easy to test; let me know your thoughts;  it's mostly just reorganizing things, the core logic is still the same

**Comment by palmerj3** [comment]
Nice work!!

**Pull request merged**
